uc_wishlist.settings:
  type: config_object
  mapping:
    default_title:
      type: string
      label: 'Default wish list title.'
    save_address:
      type: integer
      label: 'Permit a saved shipping address in a wishlist.'
    default_private:
      type: integer
      label: 'Make users wishlist private by default.'
    allow_private:
      type: integer
      label: 'Allow users to make their wishlist private.'
    default_show:
      type: integer
      label: 'Show all wish lists by default.'
    out_of_stock:
      type: integer
      label: 'Allow users to add out of stock item into wishlist.'
    default_from:
      type: string
      label: 'Specify a default From address.'
